project_id = "qfphvsyidbyhbyeyigrh"

[functions.create-shiprocket-order]
verify_jwt = false

[functions.create-checkout-order]
verify_jwt = false

[functions.confirm-paid-order]
verify_jwt = false

[functions.get-order-summary]
verify_jwt = false
