project_id = "qfphvsyidbyhbyeyigrh"

[functions.create-checkout-order]
verify_jwt = false

[functions.create-rapidshyp-order]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.confirm-paid-order]
verify_jwt = false

[functions.confirm-cod-order]
verify_jwt = false

[functions.get-order-summary]
verify_jwt = false

[functions.get-customer-history]
verify_jwt = false

[functions.admin-orders]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false
